name: Translation PR PoC
on:
  push:
    branches:
      - master
jobs:
  createTranslationsPullRequests:
    name: Create pull requests for translation forks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create pull requests
        uses: ./
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # GitHub doesn't support array for inputs (yet?)
          FORKS: |
            phanan-forks/create-translation-pull-requests
            foo/bar